#!/bin/sh

COMMAND=$1

function print_waiting_title {
  echo "------------------------------"
  echo $1
  echo "------------------------------"
  sleep 5
}

if [ -z ${COMMAND} ]; then
  echo "Usage: $0 [all, scripts, dots]"
  exit 1
fi


if [ "$COMMAND" == "all" ] || [ "$COMMAND" == "dots" ]; then
  print_waiting_title "linking dot-files"

  for file in $(echo dots/.*)
  do
    if [ -f "$file" ]; then
      filename=$(basename "$file")

      echo "----> linking $filename"

      if [ -f ~/$filename.orig ]; then
        rm ~/$filename
      else
        mv ~/$filename ~/$filename.orig
      fi

      ln -s ~/dotfiles/$file ~/$filename
    fi
  done
fi

if [ "$COMMAND" == "all" ] || [ "$COMMAND" == "scripts" ]; then
  print_waiting_title "installing scripts"

  chmod +x scripts/*

  for file in $(echo scripts/*)
  do
    echo "--> executing $file"

    ./$file
  done
fi