#!/bin/bash

if ! type "brew" > /dev/null; then
  echo ".... brew install"
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

echo ".... updating brew"
brew update && brew upgrade && brew cleanup

if ! type "git" > /dev/null; then
  echo ".... installing git"
  brew install git
fi

echo ".... installing tig"
brew install tig

echo ".... installing diff-so-fancy"
brew install diff-so-fancy

echo ".... installing autojump"
brew install autojump

echo ".... installing ag"
brew install ag

echo ".... installing wget"
brew install wget

echo ".... installing curl"
brew install curl

echo ".... installing htop"
brew install htop

echo ".... installing awscli"
brew install awscli

echo ".... installing tmate"
brew install tmate

echo ".... brew cleanup"
brew cleanup

