#!/bin/bash

echo ".... installing iterm2"
brew cask install iterm2

echo ".... configuring iterm2"
defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true
defaults write com.googlecode.iterm2 PrefsCustomFolder -string "$HOME/dotfiles/.config/iTerm"