#!/bin/bash

if ! type "zsh" > /dev/null; then
  cd ~
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  chsh -s $(which zsh) $(whoami)
  source ~/.bash_profile
  source ~/.zshrc
fi
