#!/bin/bash
ATOM_SETTINGS_PATH=/Users/$(whoami)/.atom
DOTFILES_PATH=/Users/$(whoami)/dotfiles

brew cask install atom

sleep 5

if [ -f "/usr/local/bin/apm" ]; then
  echo "--> apm command exists"
else
  ln -s /Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/apm /usr/local/bin/apm
fi

if [ -f "/usr/local/bin/atom" ]; then
  echo "--> atom command exists"
else
  ln -s /Applications/Atom.app/Contents/Resources/app/atom.sh /usr/local/bin/atom
fi

if [ -d "$ATOM_SETTINGS_PATH" ]; then
  echo "--> .atom folder exists"
else
  mkdir "$ATOM_SETTINGS_PATH"
fi

for file in $(echo .config/atom/*)
do
  filePath="$DOTFILES_PATH/$file"
  newFilePath="$ATOM_SETTINGS_PATH/$(basename $file)"
  origFilePath="$newFilePath.orig"

  if [ -f "$newFilePath" ]; then
    if [ -f "$origFilePath" ]; then
      rm $newFilePath
    else
      mv $newFilePath $origFilePath
    fi
  fi

  ln -s $filePath $newFilePath
done

cd $ATOM_SETTINGS_PATH
apm install --packages-file package-list.txt
