#!/bin/bash

if ! type "code" > /dev/null; then
  brew cask install visual-studio-code
fi

CODE_SETTINGS_PATH=/Users/$(whoami)/Library/Application\ Support/Code/User
DOTFILE_SETTINGS_PATH=/Users/$(whoami)/dotfiles/.config/vscode

sleep 5

# show extensions installed: `code --list-extensions`
# installing all extensions
code --install-extension castwide.solargraph
code --install-extension chenxsan.vscode-standardjs
code --install-extension christian-kohler.npm-intellisense
code --install-extension Equinusocio.vsc-material-theme
code --install-extension gogocrow.jsx-beautify
code --install-extension jprestidge.theme-material-theme
code --install-extension mohsen1.prettify-json
code --install-extension ms-python.python
code --install-extension ms-vscode.sublime-keybindings
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension otoniel-isidoro.vscode-ruby-ctags
code --install-extension PeterJausovec.vscode-docker
code --install-extension PKief.material-icon-theme
code --install-extension rebornix.ruby
code --install-extension redhat.java
code --install-extension taichi.react-beautify
code --install-extension trinm1709.dracula-theme-from-intellij
code --install-extension dkundel.vscode-new-file

# copy settings
if [ -f "$CODE_SETTINGS_PATH/settings.json" ]; then
  if [ -f "$CODE_SETTINGS_PATH/settings.json.orig" ]; then
    rm "$CODE_SETTINGS_PATH/settings.json"
  else
    mv "$CODE_SETTINGS_PATH/settings.json" "$CODE_SETTINGS_PATH/settings.json.orig"
  fi
fi
ln -s "$DOTFILE_SETTINGS_PATH/settings.json" "$CODE_SETTINGS_PATH/settings.json"

# copy keybindings
if [ -f "$CODE_SETTINGS_PATH/keybindings.json" ]; then
  if [ -f "$CODE_SETTINGS_PATH/keybindings.json.orig" ]; then
    rm "$CODE_SETTINGS_PATH/keybindings.json"
  else
    mv "$CODE_SETTINGS_PATH/keybindings.json" "$CODE_SETTINGS_PATH/keybindings.json.orig"
  fi
fi
ln -s "$DOTFILE_SETTINGS_PATH/keybindings.json" "$CODE_SETTINGS_PATH/keybindings.json"
