#!/bin/bash

ME=$(whoami)

SUBLIME_SETTINGS_PATH=/Users/$ME/Library/Application\ Support/Sublime\ Text\ 3/Packages/User
DOTFILE_SETTINGS_PATH=/Users/$ME/dotfiles/sublime

if [ -f "$SUBLIME_SETTINGS_PATH/Preferences.sublime-settings.orig" ]; then
  rm "$SUBLIME_SETTINGS_PATH/Preferences.sublime-settings"
else
  mv "$SUBLIME_SETTINGS_PATH/Preferences.sublime-settings" "$SUBLIME_SETTINGS_PATH/Preferences.sublime-settings.orig"
fi

if [ -f "$SUBLIME_SETTINGS_PATH/Package\ Control.sublime-settings.orig" ]; then
  rm "$SUBLIME_SETTINGS_PATH/Package\ Control.sublime-settings"
else
  mv "$SUBLIME_SETTINGS_PATH/Package\ Control.sublime-settings" "$SUBLIME_SETTINGS_PATH/Package\ Control.sublime-settings.orig"
fi

ln -s "$DOTFILE_SETTINGS_PATH/Preferences.sublime-settings" "$SUBLIME_SETTINGS_PATH/Preferences.sublime-settings"
ln -s "$DOTFILE_SETTINGS_PATH/Package\ Control.sublime-settings" "$SUBLIME_SETTINGS_PATH/Package\ Control.sublime-settings"
